=== sevaergdm/foundational-models/schema/foundational_model_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "urn:foundational-models:id:foundational-model",
  "title": "Foundational Model",
  "description": "The canonical schema for all foundational models",
  "type": "object",
  "properties": {
    "name": {
      "description": "The name of the entity",
      "type": "string"
    },
    "description": {
      "description": "A human readable description of the entity",
      "type": "string"
    },
    "owner": {
      "description": "The team who owns the entity",
      "type": "string"
    },
    "version": {
      "description": "The current version of the entity following SemVer 2.0",
      "type": "string"
    },
    "system_of_record": {
      "description": "The system which is responsible for the entity and considered the source of truth",
      "type": "string"
    },
    "lifecycle_state": {
      "description": "The current lifecycle state of the entity",
      "type": "string",
      "enum": [
        "active",
        "deprecated"
      ]
    },
    "primary_key": {
      "description": "The primary key of the entity, generally something like <entity_name>_id",
      "oneOf": [
        {
          "type": "string"
        },
        {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      ]
    },
    "attributes": {
      "description": "The attributes describing the entity",
      "type": "array",
      "items": {
        "$ref": "#/$defs/attribute"
      }
    },
    "relationships": {
      "description": "The relationships to other entities",
      "type": "array",
      "items": {
        "$ref": "#/$defs/relationship"
      }
    },
    "entity_type": {
      "description": "The type of entity, disginguishing from foundational and associative entities",
      "type": "string",
      "enum": [
        "foundational",
        "associative"
      ]
    }
  },
  "required": [
    "name",
    "description",
    "owner",
    "version",
    "system_of_record",
    "lifecycle_state",
    "primary_key",
    "attributes",
    "entity_type"
  ],
  "additionalProperties": false,
  "$defs": {
    "attribute": {
      "description": "A self-describing attribute of an entity",
      "type": "object",
      "properties": {
        "name": {
          "description": "The name of the attribute",
          "type": "string"
        },
        "description": {
          "description": "A human readable description of the attribute",
          "type": "string"
        },
        "data_type": {
          "description": "The data type of the attribute adhering to JSON data types",
          "type": "string",
          "enum": [
            "object",
            "string",
            "integer",
            "number",
            "array",
            "boolean",
            "null"
          ]
        },
        "data_format": {
          "description": "The format of the attribute if applicable, adhering to subset of available json formats",
          "oneOf": [
            {
              "type": "string",
              "enum": [
                "uuid",
                "email",
                "uri",
                "date-time",
                "date"
              ]
            },
            {
              "type": "object",
              "properties": {
                "enum": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              },
              "required": [
                "enum"
              ],
              "additionalProperties": false
            }
          ]
        },
        "items": {
          "description": "The schema for items of an array type",
          "$ref": "#/$defs/attribute-items"
        }
      },
      "required": [
        "name",
        "description",
        "data_type"
      ],
      "additionalProperties": false
    },
    "attribute-items": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "enum": ["object"]
        },
        "required": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "properties": {
          "type": "object",
          "patternProperties": {
            ".*": {
              "$ref": "#/$defs/attribute"
            }
          }
        }
      },
      "required": [
        "type",
        "required",
        "properties"
      ],
      "additionalProperties": false
    },
    "relationship": {
      "description": "The relationship between two entities",
      "type": "object",
      "properties": {
        "related_entity": {
          "description": "The target entity for the relationship",
          "type": "string"
        },
        "relationship_type": {
          "description": "The kind of relationship between the entities",
          "type": "string",
          "enum": [
            "contains",
            "is_a",
            "references"
          ]
        },
        "related_attribute": {
          "description": "The attribute in the current entity that serves as the foreign key to the related entity",
          "type": "string"
        }
      },
      "required": [
        "related_entity",
        "relationship_type",
        "related_attribute"
      ]
    },
    "additionalProperties": false
  }
}

=== sevaergdm/foundational-models/samples/product.json
{
  "name": "Product",
  "description": "A physical or digital good or service offered for sale",
  "owner": "product-team",
  "version": "1.1.0",
  "system_of_record": "product-catalog-service",
  "lifecycle_state": "active",
  "primary_key": [
    "product_id"
  ],
  "attributes": [
    {
      "name": "product_id",
      "description": "The unique identifier for the product",
      "data_type": "string",
      "data_format": "uuid"
    },
    {
      "name": "name",
      "description": "The name of the product",
      "data_type": "string"
    },
    {
      "name": "price",
      "description": "The price of the product",
      "data_type": "number"
    },
    {
      "name": "sku",
      "description": "The stock keeping unit identifier",
      "data_type": "string"
    },
    {
      "name": "available_on",
      "description": "The date the product was first available",
      "data_type": "string",
      "data_format": "date"
    },
    {
      "name": "retired_on",
      "description": "The date when the product was retired",
      "data_type": "string",
      "data_format": "date"
    }
  ],
  "entity_type": "foundational"
}

=== sevaergdm/foundational-models/entities/workspace.json
{
  "name": "workspace",
  "description": "The conceptual hub of relationships between users, resources, billing and entitlements in SAAS.",
  "owner": "client-infrastructure",
  "version": "1.0.0",
  "system_of_record": "workspace-service",
  "lifecycle_state": "active",
  "primary_key": [
    "workspace_id"
  ],
  "attributes": [
    {
      "name": "workspace_id",
      "description": "The unique identifier of a workspace",
      "data_type": "string",
      "data_format": "uuid"
    },
    {
      "name": "workspace_name",
      "description": "The name of the workspace",
      "data_type": "string"
    },
    {
      "name": "created_at",
      "description": "The timestamp when the workspace was created",
      "data_type": "string",
      "data_format": "date-time"
    }
  ],
  "relationships": [
    {
      "related_entity": "workspace_member",
      "related_attribute": "workspace_id",
      "relationship_type": "contains"
    }
  ],
  "entity_type": "foundational"
}

=== sevaergdm/foundational-models/entities/workspace_member.json
{
  "name": "workspace_member",
  "description": "A user who is a member of a given workspace",
  "owner": "client-infrastructure",
  "version": "1.0.0",
  "system_of_record": "workspace-service",
  "lifecycle_state": "active",
  "primary_key": [
    "workspace_id",
    "keycloak_user_id"
  ],
  "attributes": [
    {
      "name": "workspace_id",
      "description": "The unique identifier of a workspace",
      "data_type": "string",
      "data_format": "uuid"
    },
    {
      "name": "keycloak_user_id",
      "description": "The unique identifier of a keycloak user",
      "data_type": "string",
      "data_format": "uuid"
    },
    {
      "name": "role",
      "description": "The role assigned to the user in the workspace",
      "data_type": "string",
      "data_format": {
        "enum": [
          "admin",
          "member"
        ]
      }
    },
    {
      "name": "inserted_at",
      "description": "The timestamp when the user became a member of the workspace",
      "data_type": "string",
      "data_format": "date-time"
    },
    {
      "name": "removed_at",
      "description": "The timestamp when the user was removed as a member of the workspace",
      "data_type": "string",
      "data_format": "date-time"
    }
  ],
  "relationships": [
    {
      "related_entity": "keycloak_user",
      "related_attribute": "keycloak_user_id",
      "relationship_type": "references"
    },
    {
      "related_entity": "workspace",
      "related_attribute": "workspace_id",
      "relationship_type": "references"
    }
  ],
  "entity_type": "associative"
}

=== sevaergdm/foundational-models/entities/keycloak_user.json
{
  "name": "keycloak_user",
  "description": "The digital identity representing a physical person",
  "owner": "client-infrastructure",
  "version": "1.0.0",
  "system_of_record": "identity-platform",
  "lifecycle_state": "active",
  "primary_key": [
    "keycloak_user_id"
  ],
  "attributes": [
    {
      "name": "keycloak_user_id",
      "description": "The unique identifier from the keycloak system",
      "data_type": "string",
      "data_format": "uuid"
    },
    {
      "name": "email",
      "description": "The email of the user",
      "data_type": "string",
      "data_format": "email"
    },
    {
      "name": "email_verified",
      "description": "Indicates whether the user email has been verified",
      "data_type": "boolean"
    },
    {
      "name": "enabled",
      "description": "Indicates whether the user account is active and can be used",
      "data_type": "boolean"
    },
    {
      "name": "realm_id",
      "description": "The keycloak namespace to which the user belongs",
      "data_type": "string"
    },
    {
      "name": "created_at",
      "description": "The timestamp when the user was created",
      "data_type": "string",
      "data_format": "date-time"
    },
    {
      "name": "identity_providers",
      "description": "The external identity providers associated with the user",
      "data_type": "array",
      "items": {
        "type": "object",
        "required": [
          "identity_provider",
          "federated_user_id",
          "federated_username"
        ],
        "properties": {
          "identity_provider": {
            "name": "identity_provider",
            "data_type": "string",
            "description": "The external identity provider that the user used to authenticate"
          },
          "federated_user_id": {
            "name": "federated_user_id",
            "data_type": "string",
            "description": "The unique identifier of the user in the external identity provider system"
          },
          "federated_username": {
            "name": "federated_username",
            "data_type": "string",
            "description": "The username of the user in the external identity provider system"
          }
        }
      }
    }
  ],
  "entity_type": "foundational"
}
